project:
  type: website
  output-dir: docs

website:
  title: "Wildfire Data Exploration"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: app1.qmd
        text: Introduction
      - href: app2.qmd
        text: Causes
      - href: app3.qmd
        text: Environmental Impacts
      - href: app4.qmd
        text: Human Societal Impacts        
      - href: about.qmd
        text: Conclusion

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false

editor: visual

